DROP TABLE "ATG_4087_BATCH_WORef";

CREATE TABLE "ATG_4087_BATCH_WORef"(
 "WORefID" IDENTITY,
 "BID" BIGINT,
 "BatchNo" CHAR(3) CASE ,
 "WO" CHAR(6) CASE ,
 "Suffix" CHAR(3) CASE ,
 "PartNo" CHAR(20) CASE ,
 PRIMARY KEY ("WORefID")
);

